local config = require("config")
local autofocus = require("autofocus")
require("mousefollow")
require("hotkeys")
autofocus.start()
hs.alert.show("Hammerspoon Config Loaded")
config.log.i("Modules loaded")
